runtime: python310  # or python39, depending on your setup

entrypoint: gunicorn -b :$PORT main:app

instance_class: F1  # optional, can choose a different instance class

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

handlers:
- url: /.*
  script: auto
